workflows:
  ionic-android:
    name: Build Ionic Android APK
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.tuempresa.tuapp"
      node: 22
      java: 17
    scripts:
      - name: Install Ionic CLI
        script: |
          npm install -g @ionic/cli
      - name: Install dependencies
        script: |
          npm install
      - name: Build Ionic App
        script: |
          ionic build
      - name: Sync Capacitor Android
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
